---

- name: Restart vault sequence
  block:
    - name: Restart Vault service
      ansible.builtin.service:
        name: vault
        state: restarted
  rescue:
    - name: Collect journalctl logs
      ansible.builtin.command:
        cmd: journalctl -u vault
      register: vault_configuration_journalctl_logs
      changed_when: no

    - name: Show journalclt logs
      ansible.builtin.debug:
        msg: "{{ vault_configuration_journalctl_logs }}"
