---
# handlers file for vault_configuration

- name: Reload Vault
  ansible.builtin.service:
    name: vault
    state: reloaded

- name: Restart Vault
  ansible.builtin.service:
    name: vault
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
