---
# handlers file for vault_configuration

- name: Reload systemd
  ansible.builtin.command:
    cmd: systemctl daemon-reload  # noqa: command-instead-of-module
  changed_when: yes

- name: Reload Vault
  ansible.builtin.service:
    name: vault
    state: reloaded

- name: Restart Vault
  ansible.builtin.service:
    name: vault
    state: restarted
