---
- name: converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-vault_configuration
      vault_configuration_environment:
        - name: http_proxy
          value: "http://proxy.example.com:3128"
