---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Initialize Vault
      ansible.builtin.command:
        cmd: vault operator init
      environment:
        VAULT_ADDR: "http://localhost:8200"
